version: '3.8'
services:
  my-spring-boot-app:
    build:
      context: .
      dockerfile: Dockerfile_spring_boot
    ports:
      - "8090:8090"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - WEBDRIVER_CHROME_DRIVER=http://selenium-standalone-chrome:4444/wd/hub
      - SPRING_DATASOURCE_URL=jdbc:mysql://ff14_mysql:3306/ff14
      - SPRING_REDIS_HOST=ff14_redis
      - SPRING_REDIS_PORT=6379
    networks:
      - ff14-app-network

  selenium-standalone-chrome:
    image: selenium/standalone-chrome:4.18.1
    ports:
      - "127.0.0.1:4444:4444"
    shm_size: '2g'
    networks:
      - ff14-app-network

networks:
  ff14-app-network:
    external: true